openapi: 3.0.1
info:
  title: Customer Service API
  description: API reactiva para gestionar clientes.
  version: 1.0.0
servers:
  - url: http://localhost:8086
    description: Servidor local
tags:
  - name: Customers
    description: Operaciones sobre clientes
paths:
  /api/v1/customers:
    get:
      tags:
        - Customers
      summary: Listar todos los clientes
      operationId: listCustomers
      parameters:
        - name: type
          in: query
          required: false
          description: Filtrar por tipo de cliente
          schema:
            type: string
            enum: [PERSON, BUSINESS]
      responses:
        '200':
          description: Lista de clientes
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/CustomerResponse'
        '500':
          description: Error interno del servidor
    post:
      tags:
        - Customers
      summary: Crear un nuevo cliente
      operationId: createCustomer
      requestBody:
        description: Datos del nuevo cliente
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CustomerRequest'
            examples:
              sample:
                value:
                  firstName: Juan
                  lastName: Pérez
                  email: juan.perez@example.pe
                  documentNumber: "45879632"
                  type: PERSON
                  phone: "+51 987 654 321"
                  address:
                    line1: "Av. Arequipa 1234"
                    city: Lima
                    country: Perú
                  active: true
      responses:
        '201':
          description: Cliente creado correctamente
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CustomerResponse'
        '400':
          description: Datos de la solicitud inválidos
        '500':
          description: Error interno del servidor

  /api/v1/customers/{id}:
    get:
      tags:
        - Customers
      summary: Obtener cliente por ID
      operationId: getCustomerById
      parameters:
        - name: id
          in: path
          required: true
          description: Identificador único del cliente
          schema:
            type: string
      responses:
        '200':
          description: Cliente encontrado
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CustomerResponse'
        '404':
          description: Cliente no encontrado
    put:
      tags:
        - Customers
      summary: Actualizar un cliente existente
      operationId: updateCustomer
      parameters:
        - name: id
          in: path
          required: true
          description: Identificador único del cliente
          schema:
            type: string
      requestBody:
        description: Datos actualizados del cliente
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CustomerRequest'
      responses:
        '200':
          description: Cliente actualizado correctamente
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CustomerResponse'
        '404':
          description: Cliente no encontrado
    delete:
      tags:
        - Customers
      summary: Eliminar un cliente
      operationId: deleteCustomer
      parameters:
        - name: id
          in: path
          required: true
          description: Identificador único del cliente
          schema:
            type: string
      responses:
        '204':
          description: Cliente eliminado correctamente
        '404':
          description: Cliente no encontrado

components:
  schemas:
    CustomerRequest:
      type: object
      properties:
        firstName:
          type: string
          description: Nombres del cliente
        lastName:
          type: string
          description: Apellidos del cliente
        email:
          type: string
          format: email
          description: Correo electrónico del cliente
        documentNumber:
          type: string
          description: Número de documento del cliente (DNI, pasaporte, etc.)
        type:
          type: string
          description: Tipo de cliente
          enum: [PERSON, BUSINESS]
        phone:
          type: string
          description: Teléfono del cliente
        address:
          type: object
          description: Dirección del cliente
          properties:
            line1:
              type: string
              description: Dirección (calle y número)
            city:
              type: string
              description: Ciudad
            country:
              type: string
              description: País
        active:
          type: boolean
          description: Estado del cliente (activo o inactivo)
      required:
        - firstName
        - lastName
        - documentNumber
        - type

    CustomerResponse:
      allOf:
        - $ref: '#/components/schemas/CustomerRequest'
        - type: object
          properties:
            id:
              type: string
              description: Identificador único del cliente
            createdAt:
              type: string
              format: date-time
              description: Fecha de creación del cliente
